### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by leon0516** [Alrash/WebAuthenticate#1]
你好我是滨江的,请教个问题,我是使用openwrt路由器,DHCP可以获取到ip,但是无法打开认证页面,请问你有没有遇到过这种问题?谢谢

**Comment by Alrash** [comment]
@leon0516 没有刷过路由器，这个不太清楚。平常用的时候，好像没有出现这种情况

**Comment by leon0516** [comment]
路由器问题，换了个路由器就好了，谢谢
