### ISSUE TITLE
南信大滨江教务验证码自动填充油猴脚本好像失效了，能更新一下吗

### ISSUE THREAD

**Issue by maplefz** [Alrash/WebAuthenticate#2]
南信大滨江教务验证码自动填充油猴脚本好像失效了，能更新一下吗。谢谢

**Comment by Alrash** [comment]
@maplefz 那个东西原本验证码写在了cookie里面我直接调出来填充进去；刚才去看了一下，现在没了，我暂时没有办法 orz
